AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    stepfunctionstarter-tests

    Sample SAM Template for stepfunctionstarter-tests

Globals:
    Function:
        Timeout: 3

Resources:
    TestFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/intTest/
            Handler: app.lambdaHandler
            Runtime: nodejs14.x
            Policies:
                - CloudFormationDescribeStacksPolicy: {}
                - CodePipelineLambdaExecutionPolicy: {}

Outputs:
    IntTestFunction:
        Description: 'Hello World Lambda Function ARN'
        Value: !GetAtt TestFunction.Arn
